projectName: CollectCalls
projectUrl: https://joelpurra.com/projects/collectcalls/
projectRedirectBaseUrl: https://joelpurra.com/projects/collectcalls/docs
projectGithub: https://github.com/joelpurra/collectcalls
projectStackoverflow: https://stackoverflow.com/search?q=collectcalls
